### ISSUE TITLE
ESP32  locked at "Everything: Sending: water1 dry"

### ISSUE THREAD

**Issue by elfege** [DanielOgorchock/ST_Anything#132] opened 2018-05-28 03:05 UTC
Hi and, first, thanks for this awesome work! I'm using without difficulty your code for ESP8266 but I'm struggling with ESP32. I think I've followed all the steps regarding the ST_Anything_Multiples_ESP32WiFi.ino sketch, up to having a child device created as "water1". 

But, for some reason, everytime I start the sketch, it gets stuck here : 

> PS_Water::Analog Pin value is 0 vs limit of 500 

> Everything: Sending: water1 dry

It's a complete mystery. The arduino loop() routine is obviously not running and I made sure to copy-paste the entire original code, I only modified the wifi and ip settings, of course. Each time I reset the board, the HUB receives the "water" status and the event is generated accordingly, but anything (if I may say) else is like stuck and the "water1" port won't refresh if I change the current status (3.3V with A 1MOhm resistor for simulation purpose). I also tried without anything connected to the ESP, tried a new ESP, to no avail. I do get the creation of the "water1" child device, but nothing else beside the new status of the sensor1 after each reset of the board. 

Here is the entire log I get, if anybody know what I might be doing wrong, let me know for at this stage I'm stuck... Thank you very much for whoever may help me with this. 

 Everything: init started
Everything: Free RAM = -1
Disabling ESP32 WiFi Access Point

Initializing ESP32 WiFi network.  Please be patient...
Attempting to connect to WPA SSID: xxxxxxxxxxxxx
.......[WiFi-event] event: 7
WiFi connected
IP address: 
192.168.10.207
[WiFi-event] event: 7
WiFi connected
IP address: 
192.168.10.207

Enter the following three lines of data into ST App on your phone!
localIP = 192.168.10.207
serverPort = 8090
MAC Address = B4E62D976FDD

SSID = xxxxxxxxxxxxx
PASSWORD = xxxxxxxxxxxxxxxxxxxx
hubIP = 192.168.10.145
hubPort = 39500
RSSI = -43

SmartThingsESP32WiFI: Intialized

Everything: init ended
Everything: Free RAM = -1
Everything: adding sensor named water1
Everything: Free RAM = -1
Everything: adding sensor named water2
Everything: Free RAM = -1
Everything: adding sensor named illuminance1
Everything: Free RAM = -1
Everything: adding sensor named illuminance2
Everything: Free RAM = -1
Everything: adding sensor named voltage1
Everything: Free RAM = -1
Everything: adding sensor named smoke1
Everything: Free RAM = -1
Everything: adding sensor named temphumid1
Everything: Free RAM = -1
Everything: adding sensor named temperature2
Everything: Free RAM = -1
Everything: adding sensor named motion1
Everything: Free RAM = -1
Everything: adding sensor named motion2
Everything: Free RAM = -1
Everything: adding sensor named contact1
Everything: Free RAM = -1
Everything: adding sensor named contact2
Everything: Free RAM = -1
Everything: adding sensor named smoke2
Everything: Free RAM = -1
Everything: adding sensor named button1
Everything: Free RAM = -1
Everything: adding sensor named button2
Everything: Free RAM = -1
Everything: adding sensor named carbonMonoxide1
Everything: Free RAM = -1
Everything: adding sensor named doorControl1
Everything: Free RAM = -1
Everything: adding sensor named relaySwitch1
Everything: Free RAM = -1
Everything: adding executor named switch1
Everything: Free RAM = -1
Everything: adding executor named alarm1
Everything: Free RAM = -1
Everything: adding executor named alarm2
Everything: Free RAM = -1
Everything: initDevices started
Everything: Free RAM = -1
PS_Water::Analog Pin value is 0 vs limit of 500
Everything: Sending: water1 dry

**Comment by elfege** [comment] 2018-05-28 07:46
Now I'm trying to implement OTA. I get the ESP32 with the ST_Everything sketch to broadcast and even start upload, but it eventually fails. Any suggestion?

**Comment by mlampkin** [comment] 2018-05-30 03:02
This is a duplicate of #128. You are seeing the result of the code not breaking on errno -1 when it tries to read data from an empty buffer / disconnected ( though evidently not fully qualified as disconnected ) connection to the smarthings hub.

**Comment by ogiewon** [comment] 2018-06-05 23:16
Fix has been pushed.  Please grab latest SmartThingsESP32WIFI.cpp.

**Closed by ogiewon** 2018-06-05 23:16 UTC
