### ISSUE TITLE
Unable to add child device

### ISSUE THREAD

**Issue by jkotecki** [DanielOgorchock/ST_Anything#200] opened 2020-05-11 03:18 UTC
I downloaded the latest code and I added the Parent device in my SmartThings IDE. In the app, when I go to add my child device, I fill out all the fields but it still tells me to "Please fill out all required fields."
![image](https://user-images.githubusercontent.com/11475929/81521190-76347600-9314-11ea-8792-13885c271688.png)

My ESP seems like it's flashed correctly:
Initializing ESP8266 WiFi network.  Please be patient...
Attempting to connect to WPA SSID: Mos_Eisley
..............

Enter the following three lines of data into ST App on your phone!
localIP = 192.168.1.251
serverPort = 8090
MAC Address = 5CCF7F72F58F

SSID = Mos_Eisley
PASSWORD = password
hubIP = 192.168.1.7
hubPort = 39500
RSSI = -62
hostName = OfficeESP

SmartThingsESP8266WiFI: Intialized

Disabling ESP8266 WiFi Access Point

ArduinoOTA Ready
IP address: 192.168.1.251
ArduionOTA Host Name: OfficeESP

Everything: init ended

**Comment by jkotecki** [comment] 2020-05-11 03:45
I downloaded the device handler code from the previous commit (https://github.com/DanielOgorchock/ST_Anything/tree/b284d8de52589dc58ffb96de9d407e52da803451) and that works fine.

**Comment by ogiewon** [comment] 2020-05-11 14:46
Did you “upgrade” an existing Parent Device?  Or was this for a brand new installation?

**Comment by ogiewon** [comment] 2020-05-11 14:50
One more thing...  in your 1st screenshot, there is a red banner at the top...  did you click the tiny white X to close that warning?  Underneath it is a SAVE button that has to be pressed.

**Comment by jkotecki** [comment] 2020-05-11 14:59
I removed all old devices and started from scratch. The banner at the top is what I get when I click the Save button. Like I mentioned, I removed all code a second time and used the commit before the latest and it works fine. I think the issue is with the modification that doesn't require setting the number of buttons.

**Comment by hjung110** [comment] 2020-05-11 17:38
I have the same problem. I posted the issue on the smart things community board. The only way I was able to work around the issue is to go to the developer console and edit the preferences. I am still having other issues with my wemos D1 mini's. I am not sure if there was a hub update but for some reason I can no longer communicate with my devices

**Comment by ogiewon** [comment] 2020-05-11 23:42
So, I just created a brand new Parent Device in SmartThings.  I configured it via the ST Classic App on my iPhone.  I did not have any issues with the Settings page.  I was able to save the settings, which then resulted in the DeviceNetworkID of the Parent Device getting set to the MAC address of the ST_Anything board (a NodeMCU ESP8266.)  All child devices were created and work fine.

Are you using the ST Classic App on Android or iOS?  Perhaps it's an Android issue?

NOTE:  I did have to reboot my ST v2 Hub again to get decent performance.  It seems every time ST updates the Hub Firmware (happened 1 week ago), that I have to pull the power cord on the hub to get it to work properly again.  YMMV, of course.

**Comment by hjung110** [comment] 2020-05-11 23:48
I am using Android on a Note 10. It is interesting that the app works better on iOS versus Android since its now owned by Samsung. "face palm". I can reach out to a contact I have at smart things to see if there are any known issues being tracked on the performance issue after hub firmware updates.

**Comment by jkotecki** [comment] 2020-05-11 23:59
I am using the classic app on a Pixel 3 (Android).

**Comment by ogiewon** [comment] 2020-05-12 02:21
OK, so maybe it is an Android versus iOS issue...  I might be able to borrow my son's Android phone for a quick test.

**Comment by ogiewon** [comment] 2020-05-14 22:37
I have discovered that this issue is indeed an Android specific problem.  I have made some tweaks to the Parent Driver to resolve it.  Please give it another try if interested.  I am going to close this issue, but please feel free to comment on it (or in the ST Community.)

**Closed by ogiewon** 2020-05-14 22:37 UTC

**Comment by hjung110** [comment] 2020-05-15 00:00
I just updated the libraries and tried to update the device handlers in smartthings. Tested and still got the same error

**Comment by ogiewon** [comment] 2020-05-15 03:18
The updated Parent ST_Anything Ethernet DTH is all that was changed. Make sure the version you have is the latest and that you remembered to PUBLISH it.

**Comment by hjung110** [comment] 2020-05-15 12:14
Rookie mistake on my part. I tried to update the repo and it had no changes. When I went to view differences I saw my local copy was the old version. I updated my local copy ran the test and everything works on my end now.

**Comment by hjung110** [comment] 2020-05-15 13:00
> So, I just created a brand new Parent Device in SmartThings. I configured it via the ST Classic App on my iPhone. I did not have any issues with the Settings page. I was able to save the settings, which then resulted in the DeviceNetworkID of the Parent Device getting set to the MAC address of the ST_Anything board (a NodeMCU ESP8266.) All child devices were created and work fine.
> 
> Are you using the ST Classic App on Android or iOS? Perhaps it's an Android issue?
> 
> NOTE: I did have to reboot my ST v2 Hub again to get decent performance. It seems every time ST updates the Hub Firmware (happened 1 week ago), that I have to pull the power cord on the hub to get it to work properly again. YMMV, of course.

I followed up with a contact i have and the hub during the upgrade firmware process is set to reboot as the last step to finalize all changes within the hub. I haven't experienced any issues during any of my upgrades. If its hanging its probably due to the reboot command failing and keeping our device in a hung state.
