### ISSUE TITLE
Child device creation failed.

### ISSUE THREAD

**Issue by bdice** [DanielOgorchock/ST_Anything#21] opened 2017-08-20 21:46 UTC
My code used to use the multiplexer, but I am trying to upgrade it to work with the new parent/child interface. I keep seeing the message:

"Child device creation failed. Please make sure that the 'null' is installed and published."

If I log the error message that is being caught, I get the following:
`physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'Child Contact Sensor' in namespace 'ogiewon' not found.`

I have added this repository [(https://github.com/DanielOgorchock/ST_Anything)](https://github.com/DanielOgorchock/ST_Anything) to the SmartThings IDE and published the devices as instructed in the README.

I tried following the forum post here but I couldn't make any of those suggestions work:
https://community.smartthings.com/t/release-st-anything-v2-8-arduino-esp8266-esp32-to-st-via-thingshield-ethernet-or-wifi/77707

Like the user Isometric_Penguin who faced this problem, I cannot get "Live Logging" to work on my computer. I am not sure what browser settings they changed, but I have tried multiple browsers on multiple computers and still can't get "Live Logging" to work.

I created a minimal example with one contact sensor. The error is being thrown for my single contact switch (`deviceName` is `contact`, `deviceNumber` is `1`). My Arduino sketch is below.
```
#include <SmartThingsThingShield.h>    //Library to provide API to the SmartThings ThingShield

// ST_Anything Library 
#include <Constants.h>       //Constants.h is designed to be modified by the end user to adjust behavior of the ST_Anything library
#include <Device.h>          //Generic Device Class, inherited by Sensor and Executor classes
#include <Sensor.h>          //Generic Sensor Class, typically provides data to ST Cloud (e.g. Temperature, Motion, etc...)
#include <Executor.h>        //Generic Executor Class, typically receives data from ST Cloud (e.g. Switch)
#include <InterruptSensor.h> //Generic Interrupt "Sensor" Class, waits for change of state on digital input 
#include <PollingSensor.h>   //Generic Polling "Sensor" Class, polls Arduino pins periodically
#include <Everything.h>      //Master Brain of ST_Anything library that ties everything together and performs ST Shield communications

#include <IS_Contact.h>      //Implements an Interrupt Sensor (IS) to monitor the status of a digital input pin

//Digital Pins
#define PIN_CONTACT_1             53  //SmartThings Capability "Contact Sensor"

void callback(const String &msg){}

void setup()
{
  static st::IS_Contact             sensor01(F("contact1"), PIN_CONTACT_1, LOW, true, 500);
  st::Everything::debug=true;
  st::Executor::debug=true;
  st::Device::debug=true;
  st::PollingSensor::debug=true;
  st::InterruptSensor::debug=true;

  st::Everything::callOnMsgSend = callback;

  //Create the SmartThings Thingshield Communications Object based on Arduino Model
  #if defined(ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_NANO) || defined(ARDUINO_AVR_MINI)   //Arduino UNO, NANO, MINI
    st::Everything::SmartThing = new st::SmartThingsThingShield(pinRX, pinTX, st::receiveSmartString);      //Use Software Serial
  #elif defined(ARDUINO_AVR_LEONARDO)  //Arduino Leonardo
    st::Everything::SmartThing = new st::SmartThingsThingShield(&Serial1, st::receiveSmartString);  //Use Hardware Serial
  #elif defined(ARDUINO_AVR_MEGA) || defined(ARDUINO_AVR_MEGA2560)  //Arduino MEGA 1280 or 2560
    st::Everything::SmartThing = new st::SmartThingsThingShield(&Serial3, st::receiveSmartString);  //Use Hardware Serial
  #else  
    //assume user is using an UNO for the unknown case
    st::Everything::SmartThing = new st::SmartThingsThingShield(pinRX, pinTX, st::receiveSmartString);               //Software Serial
  #endif  

  //Run the Everything class' init() routine which establishes communications with SmartThings
  st::Everything::init();
  
  //*****************************************************************************
  //Add each sensor to the "Everything" Class
  //*****************************************************************************
  st::Everything::addSensor(&sensor01);
  
  //*****************************************************************************
  //Initialize each of the devices which were added to the Everything Class
  //*****************************************************************************
  st::Everything::initDevices();
}

//******************************************************************************************
//Arduino Loop() routine
//******************************************************************************************
void loop()
{
  st::Everything::run();
}
```

**Comment by ogiewon** [comment] 2017-08-20 22:51
Are you sure that you are on correct ST Shard?  I don't understand the Live Logging not working at all for your account.  You may want to contact SmartThings support to see if they can assist with that particular issue.

I assume you installed the ThingShield version of the Parent Device Handler?  You didn't modify any of the Device Handlers in any way, did you?  The metadata near the top needs to be left unmodified or else the parent will not be able to create the child devices.  Also, you did PUBLISH all of the Child Device Handlers, correct?

**Comment by bdice** [comment] 2017-08-20 22:59
@ogiewon I wondered about the Shard as well, and I can't figure out how to know what shard I'm on. I referred to a list of some shards, and attempted to find more of them by testing combinations of numbers and regions. I opened "Live Logging" on each of those pages but none of them showed any content.

Yes,  have the ThingShield version of the Parent Device Handler. I didn't modify the Device Handlers except after it failed. I can make the error message show up on my phone (and in the events list) like this:

```
...
} catch (e) {
        log.error "Child device creation failed with error = ${e}"
        state.alertMessage = "Error: ${e}; deviceName: ${deviceName}; deviceNumber: ${deviceNumber}"
        //state.alertMessage = "Child device creation failed. Please make sure that the '${deviceHandlerName}' is installed and published."
        runIn(2, "sendAlert")
    }
...
```

The devices all say they are published (the ThingShield one is at the bottom, but didn't fit in the screenshot):
![devices_published](https://user-images.githubusercontent.com/3943761/29499193-31939ed4-85d1-11e7-907a-d7b629a261c2.png)

**Comment by Quiqui64** [comment] 2017-08-20 23:31
![img_0069](https://user-images.githubusercontent.com/18013175/29499397-05324040-85c5-11e7-9c7e-4b3a1f37bb0c.PNG)

**Comment by Quiqui64** [comment] 2017-08-20 23:32
Your shard should show up at the top of the screen.

**Comment by bdice** [comment] 2017-08-20 23:51
I just see "graph.api.smartthings.com" as my URL without any shard information. If I do a tracert to "graph.api.smartthings.com," I see it pointing to the na01-useast1 AWS server.

**Comment by ogiewon** [comment] 2017-08-21 01:00
Sounds like you are on the correct shard, assuming you can "see your hub" from within the IDE.  If the Live Logging feature is not working, I'd contact support to see what is going on.  

It looks like everything is set up correctly in the ST IDE.  Not sure why the child device is not being created.  Hopefully the live logging will help to explain what is going on.

**Comment by jimmyhearn** [comment] 2017-08-21 03:00
I'm having a similar issue. I've been using ST_Anything for a couple months now and its been awesome. I tried to add a new sensor in my Sketch today and the child device never populated in the app. My troubleshooting led me to removing the Thingshield from Smartthings (along with all the child devices) and re-discovering it. Now none of my sensors are being created. I made no changes to the Parent or Child device handlers and looking closer at the Arduino logging the Sketch seems to be working fine with all the sensors. Wondering if a recent update to Smartthings may have hosed something up for the child device creation.

**Comment by bdice** [comment] 2017-08-21 21:22
I called SmartThings support, and they're going to take a look at my setup. I tried replacing the spaces in `Child Contact Sensor` with underscores (`Child_Contact_Sensor`) but it didn't help. It throws the same exception and says it can't find the device. The tech looking at it said that everything appears to be correctly running on the main shard (graph.api.smartthings.com). I will post when I have more information! Let us know if you find out anything else, @jimmyhearn. 👍

**Comment by ogiewon** [comment] 2017-08-21 22:21
So, as a test I pulled out my Arduino MEGA + ThingShield to see if I could reproduce the problem.  I started with a freshly paired ThingShield.  I then went into the DEVICE tab of the ST IDE and changed the Device Handler to my Parent_ST_Anything_ThingShield device handler.  Next, I loaded the Arduino ST_Anything_Multiples_ThingShield.ino into the Arduino MEGA.  I then watched the live logging and saw every child device successfully created.

Are you using an UNO or a MEGA?  Are you sure you have the ThingShield switch in the correct D2/D3 position?  If using a MEGA, do you have the 2 jumper wires installed between pins 2+14 and 3+15?

Live logging is really the key to troubleshooting this issue.  Hopefully support with help get your account issues sorted out.

Here is what my Arduino ThingShield device looks like in the IDE after it is PAIRED, DH Updated, and Arduino booted with the ST_Anything sketch.

![thingshield](https://user-images.githubusercontent.com/5206084/29540617-6ec91442-869d-11e7-82a3-f7a211edbbbe.PNG)

**Comment by jimmyhearn** [comment] 2017-08-22 12:57
So I followed your lead to start fresh, I removed the Parent and Child device handlers and recreated them and the child devices populated immediately. Not sure what happened but all is well now.

**Comment by bdice** [comment] 2017-08-23 12:20
Thanks for your testing, @ogiewon and @jimmyhearn. I am going to try again right now, following your steps. In the meantime, I received a reply from the SmartThings technician, copied below.

> I had a lead take a look at our end and we are not seeing any failures so it seems like the issue is somewhere in the communication between the two codes. [...] It seems that for some reason the parent app is throwing the error from line 349 and unable to pull from the DTH's name value which is either its access to the DTH's or a problem within the child apps definitions. Unfortunately, I am not a coder so Github and the SmartThings community will probably be your best source of information.

**Comment by bdice** [comment] 2017-08-23 22:01
I followed the steps above to start from scratch, but I'm still seeing the same errors. I rebooted my SmartThings Hub and deleted all my custom SmartThings device handlers beforehand. I am giving up for now, so this issue can probably be closed since nobody else can replicate it.

I ended up reverting to the older "multiplexer" style code, and everything is working that way with virtual device handlers. My initial reason to switch to the new parent/child style was that I hoped that Amazon Echo (Alexa) support would be better with the new style than the old style. Out of curiosity, does anyone know if the new style code allows for querying device status? (e.g. "Alexa, tell me the status of the garage door," or "Alexa, is the garage door open?")

**Comment by ogiewon** [comment] 2017-08-23 23:08
I don't think the "Stock Amazon Echo to SmartThings integration can interrogate the status of any device.  It can only turn on and off switches and adjust dimmer levels.

BTW - did you ever get the ST Web IDE Live Logging sorted out?  I would love to see those logs so I could try to help troubleshoot this issue some more.

**Comment by bdice** [comment] 2017-08-23 23:29
Hmm! I may need to look into this further to make something more Echo-compatible.

I was unable to resolve the live logging issues. ST Tech Support told me I was using the main shard, but I still don't see any events appearing. I'm not sure what else to try. I changed browsers, I disabled extensions, I tried other computers... no luck.

**Comment by ogiewon** [comment] 2017-08-23 23:46
Do you happen to have a second hub laying around that you could use for testing?  It really seems as though something is messed up in your ST IDE Development Environment if you see absolutley nothing in the Live Logging section.

I assume you mean that NOTHING ever appears there?  If so, I would get support to fix that for you.  It is nearly impossible to debug groovy code without the live logging feature.

Here is what mine looks like after about a minute:

![image](https://user-images.githubusercontent.com/5206084/29643186-879004be-883b-11e7-9a3d-b07d678cd730.png)

**Comment by jimmyhearn** [comment] 2017-08-24 02:09
I was also not seeing live logging but didnt expect to since the child devices were not present. Now that i have them back logging works fine...
![image](https://user-images.githubusercontent.com/31197237/29646144-492ae5b6-8847-11e7-97c1-05f2c9e6c2c4.png)

**Comment by bdice** [comment] 2017-08-24 02:24
I definitely wasn't getting any log messages with the parent/child code. I have some log messages from the multiplexer-style code, like "8:39:34 PM: debug Virtual Contact Open" when I open/close contact sensors. Previously, I thought that no logs were being sent, but now I have evidence that at least some logs are working. This is a good step forward.

One thing I have not tried is importing the parent/child code by hand, without using GitHub integration. The multiplexer-style code I have running right now was uploading by copy-paste, and it's working.

**Comment by ItsDLite** [comment] 2017-11-20 20:44
I am also having an issue with Child Devices not listing under the Parent in the SmartThings webpage. I have tried the following: 
Removing the Parent and all Children, rebooting the hub, removing all items from GitHub and reassigning them to my SmartThings hub. I am seeing that the refresh is causing the code in Arduino to refresh, but my individual smartThings "children" never add back into the device listing or under 'child devices" 

How do I manually add a device back into a parent in the "My Devices"?

**Comment by dandiodati** [comment] 2018-01-30 19:17
I also have an issue with the child devices being created. I got the code running on the arduino and all ips, mac address, and ports seem correct. On the smart things side I created the parent one, and I see events trying to create the child devices but it fails with an error creating any child devices.

On another note I am also not able to add your git repository since it says I dont have permissions (worked around by adding the devicehandler via code instead.

Here is the errors on events list. Says the device is not configured but I did configure it from the phone app. Also tried removing everything and trying again from scratch still same issue though.

<img width="1021" alt="screen shot 2018-01-30 at 12 15 10 am" src="https://user-images.githubusercontent.com/172809/35586182-02f72dee-05af-11e8-9c2a-aa26d6abd0f6.png">

**Comment by ogiewon** [comment] 2018-01-30 20:20
First - it is very challenging to notice new comments added to a "Closed Issue".  Please be sure to either ReOpen the issue, or simply create a new issue in GitHub so you comment does not go unnoticed.

Second - Since you manually created all of the Device Handlers, did you make sure you Published all of them as well?  Save then Publish for each of the Child Device Handlers.  Let me know if that makes a difference or not after hitting the Refresh Tile for the Parent Device in your ST Phone App.

Third - It would be helpful to see the "Live Logging" output from your specific Parent Device.  Please go to the "Live Logging" tab in the ST IDE and select your ST_Anything Parent Device's output (if you don't see it right away, simply hit the Refresh Tile for the Parent Device in your ST Phone App.)  Please capture the output and paste it here so I can help troubleshoot, if publishing the child devices does not solve the problem.

Hope this helps.  I recently updated the ReadMe as well.  Lots of tips in there.  Make sure you follow every step exactly as described.  You must select your Hub when manually creating the parent, for example.  MAC address must be all uppercase with no colons.  Etc...

**Comment by dandiodati** [comment] 2018-01-31 01:11
Sorry about not opening it again.

I was trying to follow the guide and added the parent device handler only(and published it).  From the documentation it appeared that the child device handlers would be created automatically so may have misunderstood that. I'll try later adding the child device handlers manually and see if that works.
Is it possible to give me person to link to your git repository so I can add it in smartthings ide directly?

**Comment by dandiodati** [comment] 2018-01-31 01:13
I meant give me permissions to access your GitHub repo from smartthings ide. 😀

**Comment by ogiewon** [comment] 2018-01-31 01:33
There is nothing needed permission-wise for

**Comment by dandiodati** [comment] 2018-01-31 17:37
So I added the child switch device handler and then then the two switches showed up. But I in the code there is also buttons:
 static st::IS_Button              sensor17(F("button1"), PIN_BUTTON1, 1000, LOW, true, 500);
  static st::IS_Button              sensor18(F("button2"), PIN_BUTTON2, 1000, LOW, true, 500);
  
But dont see any device handlers for them.

Also with the switches I see the arduino doing a send for the but in the logging there is an error causing them to not stay on. (They change to turningon but then evenually drop back to off).

<img width="1044" alt="screen shot 2018-01-31 at 9 29 05 am" src="https://user-images.githubusercontent.com/172809/35637780-1d8d3d18-066a-11e8-8c0a-c1a8413d7d7e.png">
<img width="1047" alt="screen shot 2018-01-31 at 9 29 41 am" src="https://user-images.githubusercontent.com/172809/35637795-2846a442-066a-11e8-9cf8-76da26e10f53.png">



Also in terms of adding your repository I get the following errors when doing that:
<img width="637" alt="screen shot 2018-01-31 at 9 32 43 am" src="https://user-images.githubusercontent.com/172809/35637833-3eafb3a4-066a-11e8-93f3-2ef645fd649b.png">

<img width="1071" alt="screen shot 2018-01-31 at 9 32 50 am" src="https://user-images.githubusercontent.com/172809/35637841-43c2a3ec-066a-11e8-9cb8-dbf06a19d791.png">

**Comment by ogiewon** [comment] 2018-02-01 01:31
There are no Button child devices.  Please read the ReadMe as it describes how the Button Capability is implemented. 

I would need to see your full sketch to help troubleshoot why your Switch devices are not staying on.

You are the only person who has ever had a permission issue with GitHub integration. I would recommend you submit a support ticket with SmartThings to see if they can assist.

**Closed** 2018-03-17 01:50 UTC
